spring:
  application:
    name: message-service
  config:
    import: "configserver:http://localhost:19000"
  cloud:
    config:
      name: order-service
      profile: dev
      fail-fast: true

slack:
  webhook:
    url: https://hooks.slack.com/services/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