spring:
  application:
    name: message-service
  config:
    import: "configserver:http://localhost:19000"
  cloud:
    config:
      name: order-service
      profile: dev
      fail-fast: true

slack:
  webhook:
    url: ${SLACK_WEBHOOK_KEY}