server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_manager_db
  data:
    redis:
      database: 4
  kafka:
    consumer:
      group-id: delivery-manager-service-group

logging:
  level:
    com.pathfinder.delivery_manager: DEBUG
