server:
  port: 8084

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hub_db
  data:
    redis:
      database: 2
  kafka:
    consumer:
      group-id: hub-service-group

logging:
  level:
    com.hub_service: DEBUG
